<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Promise</title>
</head>
<body>
<script>
    // resolve,reject,all,ract
    // resolve == then , reject == catch ,浏览器刷新可以在控制台看到结果
    let promise = new Promise((resolve, reject) => {
        resolve(1111);
        // reject(2222);
    });
    promise.then(response => {
        console.log('成功');
        console.log(response);
    }).catch(error => {
        console.log('失败');
        console.log(error);
    });

    // 链式
    function promise1(status) {
        return new Promise((resolve, reject) => {
            if (status) {
                console.log("第1个promise 成功");
                resolve("第1个promise 返回数据成功");
            } else {
                console.log("第1个promise 失败");
                reject("第1个promise 返回数据失败");
            }
        })
    }

    function promise2(status) {
        return new Promise((resolve, reject) => {
            if (status) {
                console.log("第2个promise 成功");
                resolve("第2个promise 返回数据成功");
            } else {
                console.log("第2个promise 失败");
                reject("第2个promise 返回数据失败");
            }
        })
    }

    promise1(true).then(response => {
        console.log(response);
        return promise2(true)     // 注意使用return 才能在后面的then中返回promise2的resolve 数据
    }).then(res => {
        console.log(res);
    }).catch(error => {
        console.log(error);
    })

    // all方法，数组内的promise必须全部成功（全部返回resolve），才执行then回调，否则只要有一个返回reject就执行catch
    Promise.all([promise1(true), promise2(true)]).then(response => {
        console.log("全部调用成功");
    }).catch(error => {
        console.log("有些调用失败");
    })

    // race方法，当执行数组内方法时，第一个内部函数（如：promise1）返回的结果是resolve，
    // 则回调外部（如：Promise）的then，否则回调外部的catch
    // 无论数组内第一个函数返回结果如何，所有函数都会执行一遍。
    Promise.race([promise1(false), promise2(true)]).then(response => {
        console.log("全部调用成功");
    }).catch(error => {
        console.log("有些调用失败");
    })
</script>
</body>
</html>